# Setup
title:               daveande
#tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://daveande.com
paginate:            20
paginate_path:       '/blog/page:num'
permalink:           '/blog/:title/'
baseurl:             ''
# Where are tags and categories displayed
tag_page: '/blog/tags'
category_page: '/blog/categories'


# About/contact
author:
  name:              David Anderson
  url:               https://twitter.com/daveande
  email:             daveande@gmail.com

sass:
  sass_dir: _scss

gems:
  - jekyll-paginate
#- jekyll-archives

#jekyll-archives:
#  enabled: ['year', 'tags']
#  layouts: 
#    year: jekyll-archives
#    tag: jekyll-archives
#  permalinks:
#    year: '/blog/:year/'
#    tag: '/blog/tag/:name/'
